using UpdatingParameters.Storages;
using UpdatingParameters.Storages.DuctInsulation;

namespace UpdatingParameters.ViewModels.DuctInsulation;

public class DuctInsulationFireproofingViewModel(DuctInsulationFireproofingDataStorage dataStorageFormulas):ElementTypeViewModelBase(dataStorageFormulas);