using UpdatingParameters.Storages.Pipes;

namespace UpdatingParameters.ViewModels.Pipes;

public class PipesInternalDiameterViewModel(PipesInternalDiameterDataStorage dataStorageFormulas) : ElementTypeViewModelBase(dataStorageFormulas);