using UpdatingParameters.Storages.Pipes;

namespace UpdatingParameters.ViewModels.Pipes;

public class PipesOuterDiameterViewModel(PipesOuterDiameterDataStorage dataStorageFormulas) : ElementTypeViewModelBase(dataStorageFormulas);