using UpdatingParameters.Storages.FlexPipes;

namespace UpdatingParameters.ViewModels.FlexPipes;

public class FlexPipesWithoutViewModel(FlexPipeWithoutDataStorage dataStorageFormulas) : ElementTypeViewModelBase(dataStorageFormulas);