using UpdatingParameters.Storages.PipeInsulationMtl;

namespace UpdatingParameters.ViewModels.PipeInsulation;

public class PipeInsulationCylindersViewModel(PipeInsulationCylindersDataStorage dataStorageFormulas) : ElementTypeViewModelBase(dataStorageFormulas);