using UpdatingParameters.Storages.Ducts;

namespace UpdatingParameters.ViewModels.Ducts;

public class DuctWithoutViewModel(DuctWithoutDataStorage dataStorageFormulas):ElementTypeViewModelBase(dataStorageFormulas);