using UpdatingParameters.Storages.Ducts;

namespace UpdatingParameters.ViewModels.Ducts;

public class DuctPlasticViewModel(DuctPlasticDataStorage dataStorageFormulas):ElementTypeViewModelBase(dataStorageFormulas);