using UpdatingParameters.Storages.Ducts;

namespace UpdatingParameters.ViewModels.Ducts;

public class FlexibleDuctsRoundViewModel(FlexibleDuctsRoundDataStorage dataStorageFormulas):ElementTypeViewModelBase(dataStorageFormulas);